import type { Metadata } from 'next';
import { poppins } from '@/styles/fonts/fonts';
import { NextAuthSessionProvider } from './providers/sessionProvider';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${poppins.className}`}>
        <NextAuthSessionProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
