import type { Metadata } from 'next';
import { poppins } from '@/styles/fonts/fonts';
import '@/styles/globals.css';
import { NextAuthSessionProvider } from './providers/sessionProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-br'>
      <body className={`${poppins.className}`}>
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
